// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: api/server/productinternal/productinternal.proto

package productinternal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProductInternalServiceClient is the client API for ProductInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductInternalServiceClient interface {
	StoreProduct(ctx context.Context, in *StoreProductRequest, opts ...grpc.CallOption) (*StoreProductResponse, error)
	FindProduct(ctx context.Context, in *FindProductRequest, opts ...grpc.CallOption) (*FindProductResponse, error)
}

type productInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductInternalServiceClient(cc grpc.ClientConnInterface) ProductInternalServiceClient {
	return &productInternalServiceClient{cc}
}

func (c *productInternalServiceClient) StoreProduct(ctx context.Context, in *StoreProductRequest, opts ...grpc.CallOption) (*StoreProductResponse, error) {
	out := new(StoreProductResponse)
	err := c.cc.Invoke(ctx, "/Product.ProductInternalService/StoreProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInternalServiceClient) FindProduct(ctx context.Context, in *FindProductRequest, opts ...grpc.CallOption) (*FindProductResponse, error) {
	out := new(FindProductResponse)
	err := c.cc.Invoke(ctx, "/Product.ProductInternalService/FindProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductInternalServiceServer is the server API for ProductInternalService service.
// All implementations must embed UnimplementedProductInternalServiceServer
// for forward compatibility
type ProductInternalServiceServer interface {
	StoreProduct(context.Context, *StoreProductRequest) (*StoreProductResponse, error)
	FindProduct(context.Context, *FindProductRequest) (*FindProductResponse, error)
	mustEmbedUnimplementedProductInternalServiceServer()
}

// UnimplementedProductInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductInternalServiceServer struct {
}

func (UnimplementedProductInternalServiceServer) StoreProduct(context.Context, *StoreProductRequest) (*StoreProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreProduct not implemented")
}
func (UnimplementedProductInternalServiceServer) FindProduct(context.Context, *FindProductRequest) (*FindProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProduct not implemented")
}
func (UnimplementedProductInternalServiceServer) mustEmbedUnimplementedProductInternalServiceServer() {
}

// UnsafeProductInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductInternalServiceServer will
// result in compilation errors.
type UnsafeProductInternalServiceServer interface {
	mustEmbedUnimplementedProductInternalServiceServer()
}

func RegisterProductInternalServiceServer(s grpc.ServiceRegistrar, srv ProductInternalServiceServer) {
	s.RegisterService(&ProductInternalService_ServiceDesc, srv)
}

func _ProductInternalService_StoreProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInternalServiceServer).StoreProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Product.ProductInternalService/StoreProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInternalServiceServer).StoreProduct(ctx, req.(*StoreProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInternalService_FindProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInternalServiceServer).FindProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Product.ProductInternalService/FindProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInternalServiceServer).FindProduct(ctx, req.(*FindProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductInternalService_ServiceDesc is the grpc.ServiceDesc for ProductInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Product.ProductInternalService",
	HandlerType: (*ProductInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreProduct",
			Handler:    _ProductInternalService_StoreProduct_Handler,
		},
		{
			MethodName: "FindProduct",
			Handler:    _ProductInternalService_FindProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/server/productinternal/productinternal.proto",
}
